Repository GiovanniFiorini/Obnoxious, pull requests merged in 2019-08, with the labels that each got.

#1 Constructive Greedy
  commons/setup_vars.py
  commons/utils.py
  heuristics/constructive_greedy.py
Labels: enhancement

#2 Syntax and Entity Refactor
  commons/setup_vars.py
  commons/utils.py
  entity/facility.py
  heuristics/constructive_greedy.py
  heuristics/mhf_greedy.py
  test.py
Labels: refactor

#3 MCHRF Greedy
  commons/facility.py
  commons/hazard.py
  commons/setup_vars.py
  commons/town.py
  commons/utils.py
  heuristics/mchrf_greedy.py
  heuristics/mhf_greedy.py
  instances/basic.json
  main.py
  test.py
Labels: enhancement, refactor

#4 Bugfixing:
  commons/facility.py
  commons/setup_vars.py
  commons/town.py
  heuristics/mchrf_greedy.py
  heuristics/mhf_greedy.py
  instances/basic.json
  obnoxious.py
Labels: bug, refactor

#5 Local Search
  commons/town.py
  heuristics/local_search.py
  instances/instance_generator.py
  obnoxious.py
Labels: enhancement, refactor

#6 Show and Execution Time
  .gitignore
  commons/facility.py
  commons/setup_vars.py
  commons/town.py
  heuristics/mchrf_greedy.py
  instances/instance_generator.py
  obnoxious.py
Labels: enhancement

#7 Fixes and Refactor
  heuristics/local_search.py
  obnoxious.py
Labels: refactor

#8 Variabe Depth Search Algorithm:
  commons/facility.py
  commons/town.py
  commons/utils.py
  heuristics/large_neighborhood_search.py
  heuristics/variable_depth_search.py
  obnoxious.py
Labels: enhancement, refactor
