Repository GiovanniFiorini/Obnoxious, pull requests merged in 2019-09, with the labels that each got.

#9 Main Menu
  commons/facility.py
  commons/setup_vars.py
  commons/utils.py
  instances/instance_generator.py
  obnoxious.py
Labels: enhancement

#10 GRASP
  commons/utils.py
  entity/hazard.py
  heuristics/grasp.py
  heuristics/large_neighborhood_search.py
  heuristics/mchrf_greedy.py
  heuristics/mhf_greedy.py
  heuristics/variable_depth_search.py
  instances/instance_generator.py
  obnoxious.py
Labels: enhancement, refactor

#11 Dev
  .gitignore
  commons/facility.py
  commons/hazard.py
  commons/setup_vars.py
  commons/town.py
  commons/utils.py
  entity/__pycache__/facility.cpython-36.pyc
  entity/__pycache__/town.cpython-36.pyc
  entity/facility.py
  entity/hazard.py
  entity/town.py
  heuristics/grasp.py
  heuristics/large_neighborhood_search.py
  heuristics/mchrf_greedy.py
  heuristics/mhf_greedy.py
  heuristics/variable_depth_search.py
  instances/instance_generator.py
  obnoxious.py
Labels: enhancement

#12 MINOR FIXES
  heuristics/mchrf_greedy.py
  heuristics/mhf_greedy.py
  obnoxious.py
Labels: refactor
